export declare const _HEADS_DATA: readonly [{
    readonly 9: readonly [0, 733];
    readonly 20: readonly [0, 733];
    readonly 21: readonly [0, 733];
    readonly 22: readonly [0, 733];
    readonly 25: readonly [3, 35];
    readonly 27: readonly [0, 743];
    readonly 31: readonly [0, 733];
    readonly 32: readonly [0, 733];
    readonly 33: readonly [0, 733];
    readonly 34: readonly [0, 733];
    readonly 35: readonly [0, 733];
    readonly 40: readonly [0, 743];
    readonly 41: readonly [0, 743];
    readonly 42: readonly [0, 743];
    readonly 50: readonly [0, 908];
    readonly 51: readonly [0, 50];
    readonly 54: readonly [3, 1];
    readonly 59: readonly [3, 1];
    readonly 60: readonly [3, 1];
    readonly 61: readonly [0, 733];
    readonly 62: readonly [3, 1];
    readonly 64: readonly [0, 733];
    readonly 65: readonly [0, 733];
    readonly 70: readonly [0, 1066];
    readonly 71: readonly [0, 1066];
    readonly 72: readonly [0, 1066];
    readonly 73: readonly [0, 70];
    readonly 85: readonly [0, 743];
    readonly 98: readonly [3, 1];
    readonly 107: readonly [3, 1];
    readonly 112: readonly [0, 733];
    readonly 114: readonly [3, 1];
    readonly 115: readonly [3, 1];
    readonly 120: readonly [3, 1];
    readonly 121: readonly [3, 1];
    readonly 125: readonly [0, 733];
    readonly 126: readonly [3, 1];
    readonly 132: readonly [3, 1];
    readonly 134: readonly [3, 1];
    readonly 135: readonly [3, 1];
    readonly 139: readonly [0, 733];
    readonly 140: readonly [3, 1];
    readonly 141: readonly [0, 733];
    readonly 143: readonly [0, 733];
    readonly 172: readonly [0, 40];
    readonly 177: readonly [3, 1];
    readonly 178: readonly [3, 1];
    readonly 203: readonly [3, 1];
    readonly 206: readonly [3, 1];
    readonly 259: readonly [0, 733];
    readonly 260: readonly [0, 743];
    readonly 353: readonly [0, 733];
    readonly 356: readonly [0, 1066];
    readonly 357: readonly [0, 1066];
    readonly 358: readonly [0, 1066];
    readonly 360: readonly [0, 440];
    readonly 362: readonly [0, 440];
    readonly 364: readonly [0, 440];
    readonly 366: readonly [0, 441];
    readonly 372: readonly [0, 743];
    readonly 375: readonly [0, 1066];
    readonly 376: readonly [0, 1066];
    readonly 377: readonly [0, 1066];
    readonly 378: readonly [0, 1066];
    readonly 382: readonly [0, 436];
    readonly 384: readonly [0, 437];
    readonly 386: readonly [0, 438];
    readonly 388: readonly [0, 439];
    readonly 391: readonly [0, 442];
    readonly 393: readonly [0, 443];
    readonly 394: readonly [0, 1066];
    readonly 396: readonly [0, 743];
    readonly 397: readonly [0, 743];
    readonly 414: readonly [0, 743];
    readonly 415: readonly [0, 743];
    readonly 416: readonly [0, 743];
    readonly 417: readonly [0, 743];
    readonly 418: readonly [0, 743];
    readonly 419: readonly [0, 743];
    readonly 420: readonly [0, 743];
    readonly 421: readonly [0, 743];
    readonly 422: readonly [0, 743];
    readonly 423: readonly [0, 743];
    readonly 425: readonly [0, 743];
    readonly 426: readonly [0, 743];
    readonly 427: readonly [0, 743];
    readonly 428: readonly [0, 743];
    readonly 429: readonly [0, 743];
    readonly 430: readonly [0, 743];
    readonly 431: readonly [0, 743];
    readonly 432: readonly [0, 743];
    readonly 435: readonly [0, 743];
    readonly 436: readonly [0, 743];
    readonly 437: readonly [0, 743];
    readonly 438: readonly [0, 743];
    readonly 439: readonly [0, 743];
    readonly 440: readonly [0, 743];
    readonly 441: readonly [0, 743];
    readonly 442: readonly [0, 743];
    readonly 443: readonly [0, 743];
    readonly 445: readonly [3, 1];
    readonly 450: readonly [0, 448];
    readonly 486: readonly [0, 844];
    readonly 487: readonly [0, 1066];
    readonly 488: readonly [0, 1066];
    readonly 489: readonly [0, 1066];
    readonly 490: readonly [0, 1066];
    readonly 491: readonly [0, 1066];
    readonly 492: readonly [0, 1066];
    readonly 493: readonly [0, 1066];
    readonly 494: readonly [0, 1066];
    readonly 495: readonly [0, 1066];
    readonly 496: readonly [0, 1066];
    readonly 497: readonly [0, 1066];
    readonly 498: readonly [0, 1066];
    readonly 501: readonly [0, 743];
    readonly 502: readonly [0, 743];
    readonly 503: readonly [0, 743];
    readonly 504: readonly [0, 743];
    readonly 505: readonly [0, 743];
    readonly 506: readonly [0, 743];
    readonly 507: readonly [0, 743];
    readonly 508: readonly [0, 743];
    readonly 509: readonly [0, 743];
    readonly 510: readonly [0, 743];
    readonly 531: readonly [0, 1066];
    readonly 566: readonly [0, 733];
    readonly 580: readonly [0, 694];
    readonly 581: readonly [0, 694];
    readonly 582: readonly [0, 628];
    readonly 583: readonly [0, 743];
    readonly 584: readonly [0, 743];
    readonly 585: readonly [0, 565];
    readonly 589: readonly [3, 1];
    readonly 590: readonly [3, 1];
    readonly 592: readonly [0, 764];
    readonly 594: readonly [3, 1];
    readonly 612: readonly [0, 107];
    readonly 615: readonly [3, 1];
    readonly 631: readonly [0, 844];
    readonly 642: readonly [0, 844];
    readonly 643: readonly [0, 844];
    readonly 644: readonly [0, 733];
    readonly 646: readonly [3, 1];
    readonly 650: readonly [0, 448];
    readonly 668: readonly [0, 1067];
    readonly 669: readonly [0, 668];
    readonly 670: readonly [0, 1067];
    readonly 671: readonly [0, 668];
    readonly 672: readonly [0, 668];
    readonly 673: readonly [3, 1];
    readonly 674: readonly [3, 1];
    readonly 675: readonly [0, 1066];
    readonly 683: readonly [0, 1066];
    readonly 688: readonly [0, 733];
    readonly 698: readonly [3, 1];
    readonly 702: readonly [3, 1];
    readonly 708: readonly [3, 1];
    readonly 709: readonly [3, 1];
    readonly 718: readonly [3, 1];
    readonly 720: readonly [3, 1];
    readonly 724: readonly [0, 733];
    readonly 725: readonly [0, 733];
    readonly 726: readonly [0, 743];
    readonly 732: readonly [0, 733];
    readonly 733: readonly [3, 1];
    readonly 734: readonly [0, 733];
    readonly 735: readonly [3, 1];
    readonly 738: readonly [0, 733];
    readonly 739: readonly [0, 733];
    readonly 746: readonly [0, 733];
    readonly 749: readonly [9, 2];
    readonly 756: readonly [3, 1];
    readonly 757: readonly [3, 1];
    readonly 758: readonly [3, 1];
    readonly 759: readonly [3, 1];
    readonly 760: readonly [3, 1];
    readonly 761: readonly [3, 1];
    readonly 762: readonly [0, 733];
    readonly 768: readonly [0, 650];
    readonly 769: readonly [0, 650];
    readonly 771: readonly [0, 87];
    readonly 772: readonly [0, 87];
    readonly 773: readonly [0, 355];
    readonly 774: readonly [0, 743];
    readonly 775: readonly [0, 743];
    readonly 777: readonly [0, 789];
    readonly 782: readonly [3, 1];
    readonly 783: readonly [3, 1];
    readonly 785: readonly [3, 1];
    readonly 786: readonly [3, 1];
    readonly 787: readonly [0, 733];
    readonly 788: readonly [3, 1];
    readonly 789: readonly [3, 1];
    readonly 790: readonly [3, 1];
    readonly 796: readonly [0, 743];
    readonly 797: readonly [0, 743];
    readonly 798: readonly [0, 743];
    readonly 799: readonly [0, 743];
    readonly 800: readonly [0, 743];
    readonly 801: readonly [0, 743];
    readonly 805: readonly [0, 1066];
    readonly 806: readonly [0, 1066];
    readonly 809: readonly [0, 1066];
    readonly 810: readonly [0, 733];
    readonly 811: readonly [0, 743];
    readonly 812: readonly [0, 733];
    readonly 813: readonly [0, 733];
    readonly 814: readonly [0, 733];
    readonly 818: readonly [0, 743];
    readonly 822: readonly [0, 733];
    readonly 823: readonly [3, 1];
    readonly 829: readonly [3, 1];
    readonly 830: readonly [3, 1];
    readonly 832: readonly [0, 578];
    readonly 833: readonly [0, 577];
    readonly 834: readonly [0, 578];
    readonly 835: readonly [0, 578];
    readonly 837: readonly [0, 836];
    readonly 838: readonly [0, 578];
    readonly 839: readonly [0, 578];
    readonly 841: readonly [0, 840];
    readonly 843: readonly [0, 842];
    readonly 846: readonly [0, 844];
    readonly 847: readonly [0, 844];
    readonly 848: readonly [0, 727];
    readonly 850: readonly [0, 642];
    readonly 851: readonly [0, 1067];
    readonly 852: readonly [3, 1];
    readonly 853: readonly [3, 1];
    readonly 856: readonly [0, 901];
    readonly 857: readonly [0, 901];
    readonly 875: readonly [0, 733];
    readonly 876: readonly [0, 733];
    readonly 877: readonly [3, 1];
    readonly 878: readonly [3, 1];
    readonly 879: readonly [0, 733];
    readonly 880: readonly [0, 733];
    readonly 881: readonly [0, 743];
    readonly 882: readonly [0, 733];
    readonly 883: readonly [0, 733];
    readonly 886: readonly [3, 1];
    readonly 887: readonly [0, 901];
    readonly 889: readonly [0, 733];
    readonly 896: readonly [0, 733];
    readonly 898: readonly [3, 1];
    readonly 900: readonly [0, 901];
    readonly 903: readonly [0, 901];
    readonly 904: readonly [0, 901];
    readonly 908: readonly [0, 25];
    readonly 909: readonly [0, 50];
    readonly 910: readonly [0, 50];
    readonly 911: readonly [0, 50];
    readonly 912: readonly [0, 50];
    readonly 913: readonly [3, 1];
    readonly 917: readonly [0, 779];
    readonly 918: readonly [0, 780];
    readonly 919: readonly [0, 780];
    readonly 920: readonly [0, 780];
    readonly 926: readonly [3, 1];
    readonly 928: readonly [0, 927];
    readonly 930: readonly [0, 929];
    readonly 931: readonly [0, 929];
    readonly 933: readonly [0, 932];
    readonly 937: readonly [12, 0];
    readonly 938: readonly [3, 1];
    readonly 939: readonly [3, 1];
    readonly 941: readonly [3, 1];
    readonly 949: readonly [0, 1066];
    readonly 950: readonly [0, 355];
    readonly 951: readonly [0, 743];
    readonly 952: readonly [0, 743];
    readonly 953: readonly [0, 743];
    readonly 954: readonly [0, 743];
    readonly 955: readonly [0, 733];
    readonly 959: readonly [0, 1066];
    readonly 960: readonly [3, 1];
    readonly 965: readonly [3, 1];
    readonly 967: readonly [8, 26];
    readonly 968: readonly [8, 26];
    readonly 972: readonly [3, 1];
    readonly 975: readonly [0, 973];
    readonly 976: readonly [3, 1];
    readonly 977: readonly [0, 976];
    readonly 978: readonly [3, 1];
    readonly 979: readonly [3, 1];
    readonly 980: readonly [3, 1];
    readonly 988: readonly [0, 855];
    readonly 991: readonly [0, 877];
    readonly 993: readonly [0, 934];
    readonly 994: readonly [0, 727];
    readonly 997: readonly [0, 996];
    readonly 998: readonly [0, 727];
    readonly 1004: readonly [0, 733];
    readonly 1010: readonly [0, 733];
    readonly 1011: readonly [3, 1];
    readonly 1012: readonly [3, 1];
    readonly 1013: readonly [3, 34];
    readonly 1014: readonly [0, 733];
    readonly 1020: readonly [0, 50];
    readonly 1021: readonly [0, 50];
    readonly 1022: readonly [3, 1];
    readonly 1023: readonly [3, 1];
    readonly 1024: readonly [3, 1];
    readonly 1026: readonly [3, 1];
    readonly 1027: readonly [3, 1];
    readonly 1028: readonly [0, 743];
    readonly 1029: readonly [0, 743];
    readonly 1030: readonly [0, 743];
    readonly 1031: readonly [0, 743];
    readonly 1032: readonly [0, 743];
    readonly 1036: readonly [3, 1];
    readonly 1037: readonly [3, 1];
    readonly 1038: readonly [0, 486];
    readonly 1039: readonly [0, 743];
    readonly 1041: readonly [0, 628];
    readonly 1042: readonly [0, 628];
    readonly 1055: readonly [0, 578];
    readonly 1057: readonly [3, 1];
    readonly 1058: readonly [0, 743];
    readonly 1059: readonly [0, 733];
    readonly 1061: readonly [0, 1060];
    readonly 1062: readonly [0, 50];
    readonly 1063: readonly [3, 1];
    readonly 1064: readonly [0, 733];
    readonly 1065: readonly [0, 733];
}, {
    readonly 1: readonly [0, 1066];
    readonly 3: readonly [0, 1066];
    readonly 7: readonly [3, 1];
}, {
    readonly 3: readonly [3, 1];
    readonly 4: readonly [3, 1];
    readonly 5: readonly [3, 1];
    readonly 6: readonly [3, 1];
    readonly 7: readonly [3, 1];
    readonly 24: readonly [0, 81];
    readonly 25: readonly [2, 24];
    readonly 26: readonly [2, 24];
    readonly 27: readonly [2, 24];
    readonly 28: readonly [2, 24];
    readonly 29: readonly [2, 24];
    readonly 30: readonly [0, 81];
    readonly 31: readonly [2, 24];
    readonly 33: readonly [2, 24];
    readonly 42: readonly [2, 40];
    readonly 43: readonly [2, 40];
    readonly 53: readonly [0, 1068];
    readonly 54: readonly [0, 1068];
    readonly 55: readonly [0, 1068];
    readonly 59: readonly [0, 1069];
    readonly 62: readonly [0, 764];
    readonly 63: readonly [0, 764];
    readonly 68: readonly [0, 1070];
    readonly 69: readonly [0, 1070];
    readonly 70: readonly [0, 1070];
    readonly 74: readonly [8, 23];
    readonly 75: readonly [8, 23];
    readonly 76: readonly [8, 23];
    readonly 77: readonly [8, 23];
    readonly 78: readonly [8, 23];
    readonly 79: readonly [8, 23];
    readonly 84: readonly [0, 947];
    readonly 85: readonly [0, 947];
    readonly 87: readonly [3, 1];
    readonly 88: readonly [3, 1];
    readonly 115: readonly [8, 23];
    readonly 116: readonly [2, 14];
    readonly 117: readonly [2, 9];
    readonly 118: readonly [2, 9];
}, {
    readonly 0: readonly [3, 1];
    readonly 2: readonly [0, 733];
    readonly 3: readonly [3, 1];
    readonly 4: readonly [0, 733];
    readonly 5: readonly [3, 1];
    readonly 6: readonly [3, 1];
    readonly 7: readonly [3, 1];
    readonly 8: readonly [3, 1];
    readonly 9: readonly [3, 1];
    readonly 10: readonly [3, 1];
    readonly 11: readonly [3, 1];
    readonly 13: readonly [3, 1];
    readonly 14: readonly [3, 1];
    readonly 15: readonly [3, 1];
    readonly 16: readonly [3, 1];
    readonly 17: readonly [3, 1];
    readonly 18: readonly [3, 1];
    readonly 19: readonly [3, 1];
    readonly 20: readonly [3, 1];
    readonly 21: readonly [3, 1];
    readonly 23: readonly [3, 1];
    readonly 24: readonly [3, 1];
    readonly 25: readonly [3, 1];
    readonly 27: readonly [3, 1];
    readonly 28: readonly [3, 1];
    readonly 29: readonly [3, 1];
    readonly 30: readonly [3, 1];
    readonly 31: readonly [3, 1];
    readonly 32: readonly [3, 1];
    readonly 33: readonly [3, 1];
    readonly 34: readonly [3, 1];
    readonly 35: readonly [3, 1];
    readonly 36: readonly [3, 1];
    readonly 38: readonly [3, 1];
    readonly 40: readonly [3, 1];
    readonly 41: readonly [3, 1];
    readonly 42: readonly [3, 1];
    readonly 43: readonly [3, 1];
    readonly 44: readonly [3, 1];
    readonly 45: readonly [3, 1];
    readonly 46: readonly [3, 1];
    readonly 47: readonly [3, 1];
    readonly 48: readonly [3, 1];
    readonly 50: readonly [3, 1];
    readonly 51: readonly [3, 1];
    readonly 52: readonly [3, 1];
    readonly 61: readonly [3, 1];
    readonly 62: readonly [0, 733];
    readonly 63: readonly [3, 1];
    readonly 64: readonly [3, 1];
    readonly 65: readonly [3, 154];
    readonly 66: readonly [3, 154];
    readonly 67: readonly [3, 157];
    readonly 68: readonly [3, 66];
    readonly 69: readonly [3, 68];
    readonly 70: readonly [3, 1];
    readonly 72: readonly [3, 1];
    readonly 73: readonly [3, 191];
    readonly 74: readonly [0, 733];
    readonly 75: readonly [0, 733];
    readonly 76: readonly [3, 1];
    readonly 77: readonly [3, 1];
    readonly 79: readonly [3, 1];
    readonly 80: readonly [0, 733];
    readonly 81: readonly [0, 733];
    readonly 82: readonly [0, 733];
    readonly 83: readonly [3, 1];
    readonly 84: readonly [3, 1];
    readonly 85: readonly [3, 1];
    readonly 86: readonly [3, 1];
    readonly 87: readonly [3, 35];
    readonly 88: readonly [0, 789];
    readonly 89: readonly [3, 1];
    readonly 90: readonly [3, 1];
    readonly 91: readonly [3, 1];
    readonly 92: readonly [3, 1];
    readonly 93: readonly [3, 1];
    readonly 94: readonly [3, 1];
    readonly 95: readonly [3, 94];
    readonly 96: readonly [0, 1067];
    readonly 97: readonly [3, 1];
    readonly 98: readonly [3, 1];
    readonly 99: readonly [3, 1];
    readonly 100: readonly [3, 1];
    readonly 101: readonly [3, 1];
    readonly 102: readonly [3, 1];
    readonly 103: readonly [3, 1];
    readonly 104: readonly [3, 1];
    readonly 105: readonly [3, 1];
    readonly 106: readonly [3, 1];
    readonly 107: readonly [3, 1];
    readonly 108: readonly [3, 1];
    readonly 109: readonly [3, 1];
    readonly 110: readonly [0, 733];
    readonly 111: readonly [3, 1];
    readonly 112: readonly [3, 1];
    readonly 113: readonly [3, 1];
    readonly 114: readonly [3, 113];
    readonly 115: readonly [3, 113];
    readonly 116: readonly [3, 1];
    readonly 117: readonly [3, 1];
    readonly 118: readonly [3, 1];
    readonly 119: readonly [3, 1];
    readonly 120: readonly [3, 1];
    readonly 121: readonly [3, 1];
    readonly 122: readonly [3, 1];
    readonly 123: readonly [3, 1];
    readonly 124: readonly [3, 1];
    readonly 125: readonly [3, 1];
    readonly 126: readonly [3, 1];
    readonly 127: readonly [3, 1];
    readonly 128: readonly [3, 1];
    readonly 129: readonly [3, 1];
    readonly 130: readonly [3, 1];
    readonly 131: readonly [3, 1];
    readonly 132: readonly [3, 1];
    readonly 133: readonly [3, 1];
    readonly 134: readonly [3, 1];
    readonly 135: readonly [3, 1];
    readonly 136: readonly [3, 1];
    readonly 137: readonly [3, 1];
    readonly 138: readonly [3, 1];
    readonly 139: readonly [3, 1];
    readonly 140: readonly [0, 733];
    readonly 141: readonly [3, 1];
    readonly 142: readonly [3, 1];
    readonly 143: readonly [3, 1];
    readonly 144: readonly [3, 1];
    readonly 145: readonly [3, 1];
    readonly 146: readonly [3, 1];
    readonly 147: readonly [3, 1];
    readonly 148: readonly [3, 1];
    readonly 149: readonly [3, 1];
    readonly 150: readonly [3, 1];
    readonly 151: readonly [3, 66];
    readonly 152: readonly [3, 1];
    readonly 153: readonly [3, 1];
    readonly 154: readonly [3, 157];
    readonly 155: readonly [3, 1];
    readonly 156: readonly [3, 1];
    readonly 157: readonly [3, 1];
    readonly 158: readonly [3, 43];
    readonly 159: readonly [3, 1];
    readonly 160: readonly [3, 66];
    readonly 161: readonly [3, 1];
    readonly 162: readonly [3, 1];
    readonly 163: readonly [3, 1];
    readonly 164: readonly [3, 163];
    readonly 165: readonly [3, 1];
    readonly 166: readonly [3, 167];
    readonly 167: readonly [3, 169];
    readonly 168: readonly [3, 167];
    readonly 169: readonly [3, 1];
    readonly 170: readonly [3, 167];
    readonly 171: readonly [3, 1];
    readonly 172: readonly [3, 1];
    readonly 173: readonly [3, 1];
    readonly 174: readonly [3, 1];
    readonly 175: readonly [3, 1];
    readonly 176: readonly [3, 1];
    readonly 177: readonly [3, 1];
    readonly 178: readonly [3, 1];
    readonly 179: readonly [3, 1];
    readonly 180: readonly [3, 1];
    readonly 181: readonly [3, 1];
    readonly 182: readonly [0, 733];
    readonly 183: readonly [0, 733];
    readonly 184: readonly [3, 1];
    readonly 185: readonly [3, 1];
    readonly 186: readonly [3, 1];
    readonly 187: readonly [0, 733];
    readonly 188: readonly [3, 1];
    readonly 190: readonly [3, 1];
}, {
    readonly 1: readonly [0, 107];
    readonly 8: readonly [4, 38];
    readonly 31: readonly [4, 30];
    readonly 32: readonly [4, 30];
    readonly 36: readonly [0, 733];
    readonly 37: readonly [0, 901];
    readonly 48: readonly [4, 45];
    readonly 53: readonly [0, 1066];
    readonly 54: readonly [0, 1066];
    readonly 79: readonly [4, 78];
    readonly 80: readonly [4, 78];
    readonly 81: readonly [4, 78];
    readonly 104: readonly [0, 743];
    readonly 107: readonly [4, 38];
    readonly 108: readonly [4, 154];
    readonly 109: readonly [4, 38];
    readonly 110: readonly [4, 154];
    readonly 111: readonly [4, 154];
    readonly 112: readonly [4, 38];
    readonly 113: readonly [4, 38];
    readonly 114: readonly [4, 154];
    readonly 115: readonly [4, 38];
    readonly 116: readonly [4, 38];
    readonly 117: readonly [4, 154];
    readonly 118: readonly [4, 154];
    readonly 119: readonly [4, 154];
    readonly 120: readonly [4, 154];
    readonly 121: readonly [4, 154];
    readonly 122: readonly [4, 38];
    readonly 123: readonly [4, 154];
    readonly 124: readonly [4, 38];
    readonly 125: readonly [4, 38];
    readonly 126: readonly [4, 38];
    readonly 129: readonly [0, 578];
    readonly 133: readonly [0, 901];
    readonly 135: readonly [0, 1068];
    readonly 136: readonly [0, 1068];
}, {
    readonly 3: readonly [3, 1];
    readonly 4: readonly [3, 1];
    readonly 11: readonly [3, 1];
    readonly 16: readonly [0, 50];
    readonly 17: readonly [3, 1];
    readonly 18: readonly [0, 743];
}, {
    readonly 0: readonly [3, 1];
}, {}, {
    readonly 6: readonly [8, 8];
    readonly 7: readonly [8, 8];
    readonly 8: readonly [0, 81];
    readonly 9: readonly [0, 81];
    readonly 13: readonly [8, 23];
    readonly 14: readonly [8, 23];
    readonly 15: readonly [8, 23];
    readonly 34: readonly [3, 1];
    readonly 35: readonly [3, 1];
    readonly 47: readonly [0, 1069];
    readonly 48: readonly [0, 1069];
    readonly 54: readonly [0, 764];
    readonly 64: readonly [8, 45];
    readonly 65: readonly [0, 743];
    readonly 66: readonly [0, 947];
    readonly 67: readonly [0, 947];
    readonly 68: readonly [8, 8];
    readonly 69: readonly [8, 8];
    readonly 72: readonly [4, 26];
}, {
    readonly 1: readonly [9, 2];
}, {
    readonly 0: readonly [3, 1];
}, {}];
export type TypeHeads = {
    "application/epub+zip": "application/zip";
    "application/vnd.amazon.mobi8-ebook": "application/x-mobipocket-ebook";
    "application/x-mobi8-ebook": "application/x-mobipocket-ebook";
    "application/mac-binhex40": "text/plain";
    "application/mathematica": "text/plain";
    "application/x-mathematica": "text/plain";
    "application/mathml+xml": "application/xml";
    "text/mathml": "application/xml";
    "application/mbox": "text/plain";
    "application/metalink+xml": "application/xml";
    "application/metalink4+xml": "application/xml";
    "application/x-wwf": "application/pdf";
    "application/wwf": "application/pdf";
    "application/xspf+xml": "application/xml";
    "application/x-xspf+xml": "application/xml";
    "application/x-windows-themepack": "application/vnd.ms-cab-compressed";
    "application/pkcs7-signature": "text/plain";
    "application/postscript": "text/plain";
    "application/raml+yaml": "application/yaml";
    "application/relax-ng-compact-syntax": "text/plain";
    "application/x-rnc": "text/plain";
    "application/rtf": "text/plain";
    "text/rtf": "text/plain";
    "application/smil+xml": "application/xml";
    "application/smil": "application/xml";
    "application/x-apple-systemprofiler+xml": "application/xml";
    "text/vnd.familysearch.gedcom": "text/plain";
    "application/x-gedcom": "text/plain";
    "text/gedcom": "text/plain";
    "video/x-javafx": "video/x-flv";
    "application/x-go-sgf": "text/plain";
    "application/x-godot-shader": "text/plain";
    "application/x-gdscript": "text/plain";
    "application/its+xml": "application/xml";
    "application/xliff+xml": "application/xml";
    "application/x-xliff": "application/xml";
    "application/toml": "text/plain";
    "application/yaml": "text/plain";
    "application/x-yaml": "text/plain";
    "text/yaml": "text/plain";
    "text/x-yaml": "text/plain";
    "application/vnd.cups-ppd": "text/plain";
    "application/vnd.ms-excel": "application/x-ole-storage";
    "application/msexcel": "application/x-ole-storage";
    "application/x-msexcel": "application/x-ole-storage";
    "zz-application/zz-winassoc-xls": "application/x-ole-storage";
    "application/vnd.ms-excel.addin.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.sheet.binary.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.sheet.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    "application/vnd.ms-excel.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
    "application/vnd.ms-powerpoint": "application/x-ole-storage";
    "application/powerpoint": "application/x-ole-storage";
    "application/mspowerpoint": "application/x-ole-storage";
    "application/x-mspowerpoint": "application/x-ole-storage";
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    "application/vnd.ms-powerpoint.slide.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.slide";
    "application/vnd.ms-powerpoint.slideshow.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
    "application/vnd.ms-powerpoint.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.presentationml.template";
    "application/vnd.ms-visio.drawing.main+xml": "application/zip";
    "application/vnd.ms-visio.template.main+xml": "application/zip";
    "application/vnd.ms-visio.stencil.main+xml": "application/zip";
    "application/vnd.ms-visio.drawing.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-visio.template.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-visio.stencil.macroEnabled.main+xml": "application/zip";
    "application/vnd.ms-word.document.macroEnabled.12": "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    "application/vnd.ms-word.template.macroEnabled.12": "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
    "application/oxps": "application/zip";
    "application/vnd.ms-xpsdocument": "application/zip";
    "application/xps": "application/zip";
    "application/vnd.ms-works": "application/x-ole-storage";
    "application/vnd.visio": "application/x-ole-storage";
    "application/msword": "application/x-ole-storage";
    "application/vnd.ms-word": "application/x-ole-storage";
    "application/x-msword": "application/x-ole-storage";
    "zz-application/zz-winassoc-doc": "application/x-ole-storage";
    "application/msword-template": "application/msword";
    "application/gml+xml": "application/xml";
    "application/x-starcalc": "application/x-ole-storage";
    "application/x-starchart": "application/x-ole-storage";
    "application/x-stardraw": "application/x-ole-storage";
    "application/x-starimpress": "application/x-ole-storage";
    "application/x-starmath": "application/x-ole-storage";
    "application/x-starwriter": "application/x-ole-storage";
    "application/x-starwriter-global": "application/x-ole-storage";
    "application/vnd.stardivision.calc": "application/x-ole-storage";
    "application/vnd.stardivision.chart": "application/x-ole-storage";
    "application/vnd.stardivision.draw": "application/x-ole-storage";
    "application/vnd.stardivision.impress": "application/x-ole-storage";
    "application/vnd.stardivision.mail": "application/x-ole-storage";
    "application/vnd.stardivision.math": "application/x-ole-storage";
    "application/vnd.stardivision.writer": "application/x-ole-storage";
    "application/vnd.stardivision.writer-global": "application/x-ole-storage";
    "application/vnd.sun.xml.calc": "application/zip";
    "application/vnd.sun.xml.calc.template": "application/zip";
    "application/vnd.sun.xml.draw": "application/zip";
    "application/vnd.sun.xml.draw.template": "application/zip";
    "application/vnd.sun.xml.impress": "application/zip";
    "application/vnd.sun.xml.impress.template": "application/zip";
    "application/vnd.sun.xml.math": "application/zip";
    "application/vnd.sun.xml.writer": "application/zip";
    "application/vnd.sun.xml.writer.global": "application/zip";
    "application/vnd.sun.xml.writer.template": "application/zip";
    "application/vnd.oasis.opendocument.text": "application/zip";
    "application/vnd.oasis.opendocument.text-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.text-template": "application/zip";
    "application/vnd.oasis.opendocument.text-web": "application/zip";
    "application/vnd.oasis.opendocument.text-master": "application/zip";
    "application/vnd.oasis.opendocument.text-master-template": "application/zip";
    "application/vnd.oasis.opendocument.graphics": "application/zip";
    "application/vnd.oasis.opendocument.graphics-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.graphics-template": "application/zip";
    "application/vnd.oasis.opendocument.presentation": "application/zip";
    "application/vnd.oasis.opendocument.presentation-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.presentation-template": "application/zip";
    "application/vnd.oasis.opendocument.spreadsheet": "application/zip";
    "application/vnd.oasis.opendocument.spreadsheet-flat-xml": "application/xml";
    "application/vnd.oasis.opendocument.spreadsheet-template": "application/zip";
    "application/vnd.oasis.opendocument.chart": "application/zip";
    "application/vnd.oasis.opendocument.chart-template": "application/zip";
    "application/vnd.oasis.opendocument.formula": "application/zip";
    "application/vnd.oasis.opendocument.formula-template": "application/zip";
    "application/vnd.oasis.opendocument.base": "application/zip";
    "application/vnd.oasis.opendocument.database": "application/zip";
    "application/vnd.sun.xml.base": "application/zip";
    "application/vnd.oasis.opendocument.image": "application/zip";
    "application/vnd.openofficeorg.extension": "application/zip";
    "application/vnd.android.package-archive": "application/java-archive";
    "video/vnd.youtube.yt": "application/zip";
    "application/vnd.youtube.yt": "application/zip";
    "application/x-xbel": "application/xml";
    "application/x-abiword": "application/xml";
    "application/x-cue": "text/plain";
    "application/x-aportisdoc": "application/vnd.palm";
    "chemical/x-pdb": "text/plain";
    "application/x-asp": "text/plain";
    "application/x-awk": "text/plain";
    "application/x-bzdvi": "application/x-bzip2";
    "application/x-bzip1-compressed-tar": "application/x-bzip1";
    "application/x-bzip2-compressed-tar": "application/x-bzip2";
    "application/x-bzip-compressed-tar": "application/x-bzip2";
    "application/x-bzip3-compressed-tar": "application/x-bzip3";
    "application/x-bzpdf": "application/x-bzip2";
    "application/x-bzpostscript": "application/x-bzip2";
    "application/vnd.comicbook-rar": "application/vnd.rar";
    "application/x-cbr": "application/vnd.rar";
    "application/x-cb7": "application/x-7z-compressed";
    "application/x-cbt": "application/x-tar";
    "application/vnd.comicbook+zip": "application/zip";
    "application/x-cbz": "application/zip";
    "application/x-rzip-compressed-tar": "application/x-rzip";
    "application/x-lrzip-compressed-tar": "application/x-lrzip";
    "application/x-raw-floppy-disk-image": "application/vnd.efi.img";
    "application/x-fd-file": "application/vnd.efi.img";
    "application/x-raw-disk-image-xz-compressed": "application/x-xz";
    "application/vnd.efi.iso": "application/vnd.efi.img";
    "application/x-cd-image": "application/vnd.efi.img";
    "application/x-iso9660-image": "application/vnd.efi.img";
    "application/x-iso9660-appimage": "application/vnd.efi.iso";
    "application/x-cdrdao-toc": "text/plain";
    "application/x-gd-rom-cue": "text/plain";
    "application/vnd.chess-pgn": "text/plain";
    "application/x-chess-pgn": "text/plain";
    "application/x-compressed-tar": "application/gzip";
    "application/x-cpio-compressed": "application/gzip";
    "application/x-csh": "text/plain";
    "application/ecmascript": "text/javascript";
    "text/ecmascript": "text/javascript";
    "application/x-designer": "application/xml";
    "text/x-kaitai-struct": "application/yaml";
    "text/x-qml": "text/plain";
    "application/x-desktop": "text/plain";
    "application/x-gnome-app-info": "text/plain";
    "application/x-fictionbook+xml": "application/xml";
    "application/x-fictionbook": "application/xml";
    "application/x-zip-compressed-fb2": "application/zip";
    "application/x-dia-diagram": "application/xml";
    "application/x-dia-shape": "application/xml";
    "application/x-fluid": "text/plain";
    "application/x-font-type1": "application/postscript";
    "application/x-gz-font-linux-psf": "application/gzip";
    "font/otf": "font/ttf";
    "application/x-font-otf": "font/ttf";
    "application/x-font-ttx": "application/xml";
    "application/x-gtk-builder": "application/xml";
    "application/x-glade": "application/xml";
    "application/x-gnuplot": "text/plain";
    "application/x-gzdvi": "application/gzip";
    "application/x-gzpdf": "application/gzip";
    "application/x-gzpostscript": "application/gzip";
    "application/java-archive": "application/zip";
    "application/x-jar": "application/zip";
    "application/x-java-archive": "application/zip";
    "text/x-groovy": "text/plain";
    "text/x-gradle": "text/x-groovy";
    "application/x-java-jnlp-file": "application/xml";
    "text/javascript": "text/plain";
    "application/x-javascript": "text/plain";
    "application/javascript": "text/plain";
    "text/jscript": "text/plain";
    "text/jscript.encode": "application/x-executable";
    "application/json": "application/json5";
    "application/json5": "application/ecmascript";
    "application/jrd+json": "application/json";
    "application/json-patch+json": "application/json";
    "application/ld+json": "application/json";
    "application/schema+json": "application/json";
    "application/x-ipynb+json": "application/json";
    "application/vnd.coffeescript": "text/plain";
    "application/x-kexiproject-sqlite2": "application/x-sqlite2";
    "application/x-kexiproject-sqlite3": "application/vnd.sqlite3";
    "application/x-vnd.kde.kexi": "application/vnd.sqlite3";
    "application/x-kexiproject-sqlite": "application/vnd.sqlite3";
    "text/vnd.trolltech.linguist": "application/xml";
    "application/x-linguist": "application/xml";
    "text/vnd.qt.linguist": "application/xml";
    "application/x-lyx": "text/plain";
    "text/x-lyx": "text/plain";
    "application/x-lz4-compressed-tar": "application/x-lz4";
    "application/x-lzip-compressed-tar": "application/x-lzip";
    "application/x-lzpdf": "application/x-lzip";
    "application/x-lzma-compressed-tar": "application/x-lzma";
    "application/x-magicpoint": "text/plain";
    "video/x-matroska": "application/x-matroska";
    "video/x-matroska-3d": "application/x-matroska";
    "audio/x-matroska": "application/x-matroska";
    "application/x-mimearchive": "multipart/related";
    "text/x-ocl": "text/plain";
    "text/x-cobol": "text/plain";
    "application/x-mobipocket-ebook": "application/vnd.palm";
    "application/x-msdownload": "application/x-executable";
    "application/x-ms-dos-executable": "application/x-executable";
    "application/x-dosexec": "application/x-msdownload";
    "application/x-ms-ne-executable": "application/x-msdownload";
    "application/vnd.microsoft.portable-executable": "application/x-msdownload";
    "application/x-bat": "text/plain";
    "application/bat": "text/plain";
    "application/x-powershell": "text/plain";
    "application/x-mswinurl": "text/plain";
    "application/x-m4": "text/plain";
    "application/x-nzb": "application/xml";
    "video/annodex": "application/annodex";
    "video/x-annodex": "application/annodex";
    "audio/annodex": "application/annodex";
    "audio/x-annodex": "application/annodex";
    "audio/ogg": "application/ogg";
    "audio/x-ogg": "application/ogg";
    "video/ogg": "application/ogg";
    "video/x-ogg": "application/ogg";
    "audio/x-vorbis+ogg": "audio/ogg";
    "audio/vorbis": "audio/ogg";
    "audio/x-vorbis": "audio/ogg";
    "audio/x-flac+ogg": "audio/ogg";
    "audio/x-oggflac": "audio/ogg";
    "audio/x-opus+ogg": "audio/ogg";
    "audio/x-speex+ogg": "audio/ogg";
    "video/x-theora+ogg": "video/ogg";
    "video/x-theora": "video/ogg";
    "video/x-ogm+ogg": "video/ogg";
    "video/x-ogm": "video/ogg";
    "application/vnd.ms-publisher": "application/x-ole-storage";
    "application/x-msi": "application/x-ole-storage";
    "application/microsoftpatch": "application/x-ole-storage";
    "application/microsoftupdate": "application/vnd.ms-cab-compressed";
    "application/appx": "application/zip";
    "application/msix": "application/zip";
    "application/appxbundle": "application/zip";
    "application/msixbundle": "application/zip";
    "application/appinstaller": "application/xml";
    "application/x-perl": "text/plain";
    "text/x-perl": "text/plain";
    "application/x-php": "text/plain";
    "application/x-qtiplot": "text/plain";
    "application/x-quicktime-media-link": "video/quicktime";
    "application/x-quicktimeplayer": "video/quicktime";
    "text/x-reject": "text/plain";
    "application/x-reject": "text/plain";
    "application/x-source-rpm": "application/x-rpm";
    "application/x-ruby": "text/plain";
    "application/x-markaby": "application/x-ruby";
    "text/x-crystal": "text/plain";
    "text/crystal": "text/plain";
    "text/julia": "text/plain";
    "text/rust": "text/plain";
    "application/x-shared-library-la": "text/plain";
    "application/x-shellscript": "text/plain";
    "text/x-sh": "text/plain";
    "application/x-fishscript": "text/plain";
    "text/x-fish": "text/plain";
    "application/x-nuscript": "text/plain";
    "text/x-nu": "text/plain";
    "application/x-subrip": "text/plain";
    "application/x-srt": "text/plain";
    "text/vtt": "text/plain";
    "application/x-sami": "text/plain";
    "text/x-microdvd": "text/plain";
    "text/x-mpl2": "text/plain";
    "text/x-mpsub": "text/plain";
    "text/x-ssa": "text/plain";
    "text/x-subviewer": "text/plain";
    "text/x-iMelody": "text/plain";
    "audio/x-iMelody": "text/plain";
    "audio/iMelody": "text/plain";
    "text/x-mrml": "application/xml";
    "application/x-tarz": "application/x-compress";
    "application/x-theme": "application/x-desktop";
    "text/troff": "text/plain";
    "application/x-troff": "text/plain";
    "text/x-troff": "text/plain";
    "application/x-troff-man": "text/plain";
    "application/x-tzo": "application/x-lzop";
    "application/x-xz-compressed-tar": "application/x-xz";
    "application/x-zstd-compressed-tar": "application/zstd";
    "application/x-xzpdf": "application/x-xz";
    "application/x-wais-source": "text/plain";
    "application/xhtml+xml": "application/xml";
    "audio/vnd.dts.hd": "audio/vnd.dts";
    "audio/x-dtshd": "audio/vnd.dts";
    "audio/x-aifc": "application/x-iff";
    "audio/x-aiffc": "application/x-iff";
    "audio/x-aiff": "application/x-iff";
    "audio/x-m4r": "video/mp4";
    "audio/x-m4b": "audio/mp4";
    "video/3gpp": "video/mp4";
    "video/3gp": "video/mp4";
    "audio/3gpp": "video/mp4";
    "video/3gpp-encrypted": "video/mp4";
    "audio/3gpp-encrypted": "video/mp4";
    "audio/x-rn-3gpp-amr": "video/mp4";
    "audio/x-rn-3gpp-amr-encrypted": "video/mp4";
    "audio/x-rn-3gpp-amr-wb": "video/mp4";
    "audio/x-rn-3gpp-amr-wb-encrypted": "video/mp4";
    "audio/x-mpegurl": "text/plain";
    "audio/mpegurl": "text/plain";
    "application/m3u": "text/plain";
    "audio/x-mp3-playlist": "text/plain";
    "audio/m3u": "text/plain";
    "audio/x-m3u": "text/plain";
    "application/vnd.apple.mpegurl": "text/plain";
    "audio/x-minipsf": "audio/x-psf";
    "audio/x-psflib": "audio/x-psf";
    "audio/x-ms-wma": "application/vnd.ms-asf";
    "audio/wma": "application/vnd.ms-asf";
    "text/vnd.rn-realtext": "text/plain";
    "audio/vnd.wave": "application/x-riff";
    "audio/wav": "application/x-riff";
    "audio/x-wav": "application/x-riff";
    "video/x-mjpeg": "image/jpeg";
    "image/openraster": "application/zip";
    "application/x-ufraw": "application/xml";
    "image/x-adobe-dng": "image/tiff";
    "image/x-canon-crw": "image/x-dcraw";
    "image/x-canon-cr2": "image/tiff";
    "image/x-canon-cr3": "image/x-dcraw";
    "image/x-fuji-raf": "image/x-dcraw";
    "image/x-kodak-dcr": "image/tiff";
    "image/x-kodak-k25": "image/tiff";
    "image/x-kodak-kdc": "image/tiff";
    "image/x-minolta-mrw": "image/x-dcraw";
    "image/x-nikon-nef": "image/tiff";
    "image/x-nikon-nrw": "image/tiff";
    "image/x-olympus-orf": "image/x-dcraw";
    "image/x-panasonic-rw": "image/x-dcraw";
    "image/x-panasonic-raw": "image/x-dcraw";
    "image/x-panasonic-rw2": "image/x-dcraw";
    "image/x-panasonic-raw2": "image/x-dcraw";
    "image/x-pentax-pef": "image/tiff";
    "image/x-sigma-x3f": "image/x-dcraw";
    "image/x-sony-srf": "image/tiff";
    "image/x-sony-sr2": "image/tiff";
    "image/x-sony-arw": "image/tiff";
    "image/apng": "image/png";
    "image/vnd.mozilla.apng": "image/png";
    "image/svg+xml": "application/xml";
    "image/svg+xml-compressed": "application/gzip";
    "image/x-bzeps": "application/x-bzip2";
    "application/docbook+xml": "application/xml";
    "application/x-docbook+xml": "application/xml";
    "application/vnd.oasis.docbook+xml": "application/xml";
    "image/vnd.djvu+multipage": "image/vnd.djvu";
    "image/x-eps": "application/postscript";
    "image/vnd.fpx": "application/x-ole-storage";
    "image/x-fpx": "application/x-ole-storage";
    "image/x-gzeps": "application/gzip";
    "image/x-ilbm": "application/x-iff";
    "image/x-iff": "application/x-iff";
    "image/x-portable-bitmap": "image/x-portable-anymap";
    "image/x-portable-graymap": "image/x-portable-anymap";
    "image/x-portable-pixmap": "image/x-portable-anymap";
    "message/rfc822": "text/plain";
    "model/iges": "text/plain";
    "model/gltf+json": "application/json";
    "model/vrml": "text/plain";
    "model/obj": "text/plain";
    "application/prs.wavefront-obj": "text/plain";
    "model/mtl": "text/plain";
    "text/calendar": "text/plain";
    "text/x-vcalendar": "text/plain";
    "application/ics": "text/plain";
    "text/css": "text/plain";
    "text/vcard": "text/plain";
    "text/directory": "text/plain";
    "text/x-vcard": "text/plain";
    "text/turtle": "text/plain";
    "text/x-txt2tags": "text/plain";
    "text/x-verilog": "text/plain";
    "text/x-svhdr": "text/x-verilog";
    "text/x-svsrc": "text/x-verilog";
    "text/x-vhdl": "text/plain";
    "application/rdf+xml": "application/xml";
    "text/rdf": "application/xml";
    "text/x-rst": "text/plain";
    "application/owl+xml": "application/xml";
    "text/richtext": "text/plain";
    "application/rss+xml": "application/xml";
    "text/rss": "application/xml";
    "application/atom+xml": "application/xml";
    "text/x-opml+xml": "application/xml";
    "text/x-opml": "application/xml";
    "text/sgml": "text/plain";
    "application/x-sylk": "text/plain";
    "text/spreadsheet": "text/plain";
    "text/tab-separated-values": "text/plain";
    "text/vnd.graphviz": "text/plain";
    "text/vnd.sun.j2me.app-descriptor": "text/plain";
    "text/vnd.wap.wml": "application/xml";
    "text/vnd.wap.wmlscript": "text/plain";
    "text/vnd.senx.warpscript": "text/plain";
    "text/x-adasrc": "text/plain";
    "text/x-bibtex": "text/plain";
    "text/x-blueprint": "text/plain";
    "text/x-c++hdr": "text/x-chdr";
    "text/x-c++src": "text/x-objc++src";
    "text/x-chdr": "text/x-csrc";
    "text/x-cmake": "text/plain";
    "text/x-common-lisp": "text/plain";
    "text/csv": "text/plain";
    "text/x-comma-separated-values": "text/plain";
    "text/x-csv": "text/plain";
    "text/csv-schema": "text/plain";
    "text/x-csrc": "text/x-objcsrc";
    "text/x-c": "text/x-objcsrc";
    "text/x-asm": "text/plain";
    "text/x-csharp": "text/plain";
    "text/x-vala": "text/plain";
    "text/x-ooc": "text/plain";
    "text/x-dcl": "text/plain";
    "text/x-dsl": "text/plain";
    "text/x-dsrc": "text/plain";
    "application/xml-dtd": "text/plain";
    "text/x-dtd": "text/plain";
    "text/x-eiffel": "text/plain";
    "text/x-emacs-lisp": "text/plain";
    "text/x-elixir": "text/plain";
    "text/x-erlang": "text/plain";
    "text/x-fortran": "text/plain";
    "text/x-genie": "text/plain";
    "text/x-gettext-translation": "text/plain";
    "text/x-po": "text/plain";
    "application/x-gettext": "text/plain";
    "text/x-gettext-translation-template": "text/plain";
    "text/x-pot": "text/plain";
    "text/x-gherkin": "text/plain";
    "text/html": "text/plain";
    "application/hta": "text/html";
    "text/x-component": "application/xml";
    "text/cache-manifest": "text/plain";
    "text/x-google-video-pointer": "text/plain";
    "text/google-video-pointer": "text/plain";
    "text/x-haskell": "text/plain";
    "text/x-idl": "text/plain";
    "text/x-java": "text/plain";
    "text/x-ldif": "text/plain";
    "text/x-lilypond": "text/plain";
    "text/x-literate-haskell": "text/plain";
    "text/x-log": "text/plain";
    "text/x-makefile": "text/plain";
    "text/markdown": "text/plain";
    "text/x-markdown": "text/plain";
    "text/x-moc": "text/plain";
    "text/x-ms-regedit": "text/plain";
    "text/x-mof": "text/x-csrc";
    "text/x-mup": "text/plain";
    "text/x-nix": "text/plain";
    "text/x-objcsrc": "text/x-objc++src";
    "text/x-objc++src": "text/plain";
    "text/x-ocaml": "text/plain";
    "text/x-opencl-src": "text/x-csrc";
    "text/x-matlab": "text/plain";
    "text/x-octave": "text/plain";
    "text/x-modelica": "text/plain";
    "text/x-pascal": "text/plain";
    "text/x-patch": "text/plain";
    "text/x-diff": "text/plain";
    "application/vnd.dart": "text/plain";
    "text/x-dart": "text/plain";
    "text/x-nim": "text/plain";
    "text/x-nimscript": "text/x-nim";
    "text/x-go": "text/plain";
    "text/x-python3": "text/x-python";
    "text/x-python2": "text/x-python";
    "text/x-python": "text/x-cython";
    "text/x-cython": "text/plain";
    "text/x-sagemath": "text/x-python";
    "text/x-lua": "text/plain";
    "text/x-nfo": "text/x-readme";
    "text/x-rpm-spec": "text/plain";
    "text/x-sass": "text/plain";
    "text/x-scala": "text/plain";
    "text/x-scheme": "text/plain";
    "text/x-scss": "text/plain";
    "text/x-setext": "text/plain";
    "application/sql": "text/plain";
    "text/x-sql": "text/plain";
    "text/tcl": "text/plain";
    "text/x-tcl": "text/plain";
    "text/x-tex": "text/plain";
    "application/x-tex": "text/plain";
    "text/x-texinfo": "text/plain";
    "text/x-typst": "text/plain";
    "text/x-troff-me": "text/plain";
    "text/x-troff-mm": "text/troff";
    "text/x-troff-ms": "text/plain";
    "text/x-twig": "text/plain";
    "text/x-uil": "text/plain";
    "text/x-uuencode": "text/plain";
    "zz-application/zz-winassoc-uu": "text/plain";
    "text/x-basic": "text/plain";
    "text/x-vb": "text/plain";
    "text/vbscript": "text/plain";
    "text/vbs": "text/plain";
    "text/vbscript.encode": "text/plain";
    "text/x-xmi": "application/xml";
    "text/x-xslfo": "application/xml";
    "text/x-iptables": "text/plain";
    "text/x-dbus-service": "text/plain";
    "text/x-systemd-unit": "text/plain";
    "application/xslt+xml": "application/xml";
    "application/xml": "text/plain";
    "text/xml": "text/plain";
    "application/xml-external-parsed-entity": "application/xml";
    "text/xml-external-parsed-entity": "application/xml";
    "video/vnd.mpegurl": "text/plain";
    "video/x-mpegurl": "text/plain";
    "application/x-netshow-channel": "application/vnd.ms-asf";
    "video/x-ms-wmv": "application/vnd.ms-asf";
    "application/sdp": "text/plain";
    "application/x-sdp": "text/plain";
    "application/vnd.sdp": "text/plain";
    "application/vnd.google-earth.kml+xml": "application/xml";
    "application/vnd.google-earth.kmz": "application/zip";
    "application/geo+json": "application/json";
    "application/vnd.geo+json": "application/json";
    "application/gpx+xml": "application/xml";
    "application/gpx": "application/xml";
    "application/x-gpx+xml": "application/xml";
    "application/x-gpx": "application/xml";
    "application/x-ica": "text/plain";
    "application/vnd.mozilla.xul+xml": "application/xml";
    "application/x-xpinstall": "application/zip";
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "application/zip";
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.slide": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "application/zip";
    "application/vnd.openxmlformats-officedocument.presentationml.template": "application/zip";
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "application/zip";
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "application/zip";
    "application/vnd.ms-officetheme": "application/zip";
    "application/x-cisco-vpn-settings": "text/plain";
    "application/x-it87": "text/plain";
    "application/x-ccmx": "text/plain";
    "application/trig": "text/plain";
    "application/x-trig": "text/plain";
    "application/vnd.apple.keynote": "application/zip";
    "application/x-iwork-keynote-sffkey": "application/zip";
    "application/vnd.apple.numbers": "application/zip";
    "application/x-iwork-numbers-sffnumbers": "application/zip";
    "application/vnd.apple.pages": "application/zip";
    "application/x-iwork-pages-sffpages": "application/zip";
    "application/vnd.apple.pkpass": "application/zip";
    "application/x-pagemaker": "application/x-ole-storage";
    "application/vnd.flatpak.repo": "text/plain";
    "application/vnd.flatpak.ref": "text/plain";
    "application/vnd.squashfs": "application/vnd.efi.img";
    "application/vnd.appimage": "application/x-executable";
    "application/vnd.snap": "application/vnd.squashfs";
    "model/3mf": "application/zip";
    "application/vnd.ms-3mfdocument": "application/zip";
    "text/x.gcode": "text/plain";
    "application/ovf": "application/x-tar";
    "application/x-virtualbox-ova": "application/x-tar";
    "application/x-pyspread-bz-spreadsheet": "application/x-bzip2";
    "text/x-kotlin": "text/plain";
    "text/x-devicetree-source": "text/plain";
    "text/org": "text/plain";
    "application/sparql-results+xml": "application/xml";
    "application/x-openvpn-profile": "text/plain";
    "application/x-modrinth-modpack+zip": "application/zip";
    "application/x-qbrew": "application/xml";
    "application/x-eris-link+cbor": "application/cbor";
    "application/vnd.gerber": "text/plain";
    "application/x-gerber": "text/plain";
    "application/x-gerber-job": "application/json";
    "application/x-excellon": "text/plain";
    "application/x-tiled-tmx": "application/xml";
    "application/x-tiled-tsx": "application/xml";
};
